### ISSUE TITLE
Inplementações #1

### ISSUE THREAD

**Issue by B0yEditi0n** [B0yEditi0n/Fichas-Conversor#6]
- [ ] Configurar os Equipamentos
- [x] Adicionar uma forma que a index.html se comunique com ficha.html
- pseudo soluções 
- integrar com o firebase
- criar um servidor local
- reler a documentação do local storage

https://developer.mozilla.org/pt-BR/docs/Web/API/Window/localStorage

**Comment by B0yEditi0n** [comment]
- [x] Adicionar string de Removivel

**Comment by B0yEditi0n** [comment]
- [x] Fixa Proporções do papel A4 e deixá-las ao meio da pagina

**Comment by B0yEditi0n** [comment]
- [x] Adicionar Tema Dark como opção

**Comment by B0yEditi0n** [comment]
- [x] Implementar um Menu de Configuração com os seguintes componentes;
- - [x] Configurações de Tema
- - [x] Incluir Força
- - [x] Tipo de Ficha Exibida

**Comment by ARKY-1** [comment]
nn ta aparecendo a ofensiva e nem que tipoo de ambiente favorito é

**Comment by B0yEditi0n** [comment]
- [ ] Adicionar Opções de Vantagens
